### ISSUE TITLE
Large filesize gifs don't show up

### ISSUE THREAD

**Issue by apellerano-pw** [kevinwuhoo/gitphy#5]
I think github strips them out if they're large enough.

e.g.

![](https://media2.giphy.com/media/Q6gPyUYrCk76g/giphy.gif?cid=e1bb72ff5a8de481365332574d7116cd)

^ (i used gitphy to do)
```![](https://media2.giphy.com/media/Q6gPyUYrCk76g/giphy.gif?cid=e1bb72ff5a8de481365332574d7116cd)```

**Comment by apellerano-pw** [comment]
Eyyy that one shows now! They must have upped the limit. Closing.

**Comment by kevinwuhoo** [comment]
I think this is actually an issue. I've had it happen to me and this was my suspicion too. Giphy's API does allow you to select downsampled gif urls which are 10mb max. I've been planning to switch to using that instead anyway because adding > 10mb to a page for a gif seems bad for battery life or data quotas.
